run:
  timeout: 5m

linters-settings:
  lll:
    line-length: 160

  errcheck:
    check-type-assertions: true

  funlen:
    lines: 120
    statements: 60

  gocognit:
    min-complexity: 25

  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: true

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

linters:
  disable-all: true
  enable:
    - lll
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gosec
    - revive
    - unconvert
    - unparam
    - whitespace
    - stylecheck
    - testifylint

issues:
  max-same-issues: 10
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
        - funlen
        - goconst
        - gosec
