services:
  marketplace:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=subscriptions_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
    volumes:
      - /home/${USER}/.pgdata:/usr/local/pgsql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d subscriptions_db" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
