services:
  subs-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail -X GET http://subs-service:8080/api/v1/health || exit 1
      interval: 15s
      timeout: 3s
      start_period: 3s
      retries: 1

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=subscriptions_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - PGDATA=/etc/.pgdata
    volumes:
      - /home/${USER}/.pgdata:/etc/.pgdata
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d subscriptions_db" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true

  tester:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - HTTP_ADDRESS=subs-service:8080
    profiles:
      - test
    depends_on:
      subs-service:
        condition: service_healthy
